
-- ridge regression 
       * evitar overfitting
        
       y=ax+b
       
       a,b = min[sum (y-y_hat)² ] ---> OLS
                       erro
       a,b = min[sum (y-y_hat)² + lambda*a²+....] ---> Ridge Regression
                       erro
       lambda é estimado via cross validation dos dados, no fundo a gente quer saber qual o lambda que  minimiza a variancia quando variamos os datasets
       
       video explicativo: https://www.youtube.com/watch?v=Q81RR3yKn30
       
       
 -lasso
 
       y=ax+b
       
       a,b = min[sum (y-y_hat)² ] ---> OLS
                       erro
       a,b = min[sum (y-y_hat)² + lambda*|a|+....] ---> lasso 
                       erro
                       
      * é tão bom quanto o Ridge regression
      * a grande diferença é que o lasso pode retirar variaveis (feature selection)
      
      
 link - Geometric interpretation of penalized linear regression
 
 Livros - 
     * Noções de Probabilidade e Estatística marcos magalhães 
 https://www.edusp.com.br/livros/nocoes-de-probabilidade-e-estatistica/

    *Morettin & Bussab - Estatística Básica
 

Lasso

In [4]:
import numpy as np
import pandas as pd
from sklearn.linear_model import Ridge, Lasso
from sklearn.metrics import mean_squared_error,r2_score
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn import model_selection
import matplotlib.pyplot as plt
from sklearn.linear_model import RidgeCV, LassoCV

In [6]:
#carregando os dados
df = pd.read_csv("C:\\Users\\luisa.bolsoni\\Documents\\ICD\\Hitters.csv")
df.head()

AtBat  Hits  HmRun  Runs  RBI  Walks  Years  CAtBat  CHits  CHmRun  CRuns  \
0    293    66      1    30   29     14      1     293     66       1     30   
1    315    81      7    24   38     39     14    3449    835      69    321   
2    479   130     18    66   72     76      3    1624    457      63    224   
3    496   141     20    65   78     37     11    5628   1575     225    828   
4    321    87     10    39   42     30      2     396    101      12     48   

   CRBI  CWalks League Division  PutOuts  Assists  Errors  Salary NewLeague  
0    29      14      A        E      446       33      20     NaN         A  
1   414     375      N        W      632       43      10   475.0         N  
2   266     263      A        W      880       82      14   480.0         A  
3   838     354      N        E      200       11       3   500.0         N  
4    46      33      N        E      805       40       4    91.5         N

In [2]:
#carregando os dados
df = pd.read_csv("C:\\Users\\luisa.bolsoni\\Documents\\ICD\\Hitters.csv")

#apagando dados nulos
df = df.dropna()

dms = pd.get_dummies(df[['League', 'Division', 'NewLeague']])

y = df["Salary"]

X_ = df.drop(['Salary', 'League', 'Division', 'NewLeague'], axis=1).astype('float64')

X = pd.concat([X_, dms[['League_N', 'Division_W', 'NewLeague_N']]], axis=1)

X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    test_size=0.25, 
                                                    random_state=42)

In [3]:
df.head()

AtBat  Hits  HmRun  Runs  RBI  Walks  Years  CAtBat  CHits  CHmRun  CRuns  \
1    315    81      7    24   38     39     14    3449    835      69    321   
2    479   130     18    66   72     76      3    1624    457      63    224   
3    496   141     20    65   78     37     11    5628   1575     225    828   
4    321    87     10    39   42     30      2     396    101      12     48   
5    594   169      4    74   51     35     11    4408   1133      19    501   

   CRBI  CWalks League Division  PutOuts  Assists  Errors  Salary NewLeague  
1   414     375      N        W      632       43      10   475.0         N  
2   266     263      A        W      880       82      14   480.0         A  
3   838     354      N        E      200       11       3   500.0         N  
4    46      33      N        E      805       40       4    91.5         N  
5   336     194      A        W      282      421      25   750.0         A

In [3]:
lasso_model = Lasso().fit(X_train,y_train)

C:\Users\luisa.bolsoni\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 8256653.399850385, tolerance: 3898.686956380658
  model = cd_fast.enet_coordinate_descent(


In [4]:
lasso_model.intercept_

-5.587450677336733

In [5]:
#sobre as variaveis que temos descobrimos o coeficiente de lasso delas

lasso_model.coef_

array([-1.74875691e+00,  8.59204135e+00,  6.67993798e+00, -3.06715333e+00,
       -1.91843070e+00,  5.32372890e+00,  8.39184117e+00, -1.63172447e-01,
       -8.22311277e-02, -3.93602861e-01,  1.71118530e+00,  6.55730545e-01,
       -6.48379405e-01,  2.59815358e-01,  2.73041157e-01, -4.41440454e-01,
        8.54474011e+01, -9.59701213e+01, -2.13086605e+01])

In [6]:
# Aqui a gente testa os diferentes lambdas

lasso = Lasso()
coefs = []
alphas = np.random.randint(0,1000,100)


for a in alphas:
    lasso.set_params(alpha = a)
    lasso.fit(X_train,y_train)
    coefs.append(lasso.coef_)

C:\Users\luisa.bolsoni\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 6471.99786381796, tolerance: 3898.686956380658
  model = cd_fast.enet_coordinate_descent(
C:\Users\luisa.bolsoni\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 4542.575368799269, tolerance: 3898.686956380658
  model = cd_fast.enet_coordinate_descent(
C:\Users\luisa.bolsoni\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 4705742.440729503, tolerance: 3898.686956380658
  model = cd_fast.enet_coordinate_descent(
C:\Users\luisa.bolsoni\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_de

C:\Users\luisa.bolsoni\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 6353.6480295322835, tolerance: 3898.686956380658
  model = cd_fast.enet_coordinate_descent(
C:\Users\luisa.bolsoni\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 4643.357592899352, tolerance: 3898.686956380658
  model = cd_fast.enet_coordinate_descent(


In [7]:
lasso_model.predict(X_train)[:5]

array([377.26270596, 786.51524513, 495.14140718, 117.19492966,
       429.04228506])

In [8]:
lasso_model.predict(X_test)[:5]

array([ 609.18826367,  696.96810702, 1009.06157391,  412.22773375,
        409.25851712])

In [9]:
y_pred = lasso_model.predict(X_test)
np.sqrt(mean_squared_error(y_test,y_pred))
#RMSE

356.0975884554033

In [10]:
#quanto maior melhor 
r2_score(y_test, y_pred)

0.4142279813236619

In [11]:
lasso_cv_model = LassoCV(alphas = np.random.randint(0,1000,100), cv = 10, max_iter = 100000).fit(X_train,y_train)

In [12]:
lasso_cv_model.alpha_

168

In [13]:
lasso_tuned = Lasso().set_params(alpha = lasso_cv_model.alpha_).fit(X_train,y_train)

y_pred_tuned = lasso_tuned.predict(X_test)

np.sqrt(mean_squared_error(y_test,y_pred_tuned))
#RMSE

362.37043165656826

In [14]:
# We know that the coefficients not used in Lasso Regression are set to zero. So let's observe.

pd.Series(lasso_tuned.coef_, index = X_train.columns )

AtBat         -1.222864
Hits           5.776365
HmRun          0.000000
Runs           0.000000
RBI            0.000000
Walks          2.970336
Years          0.000000
CAtBat        -0.165227
CHits          0.203758
CHmRun        -0.000000
CRuns          1.096077
CRBI           0.476663
CWalks        -0.242810
PutOuts        0.273508
Assists        0.185169
Errors        -0.000000
League_N       0.000000
Division_W    -0.000000
NewLeague_N    0.000000
dtype: float64

In [15]:
#Ridge Regression

In [16]:
from sklearn.linear_model import Ridge, RidgeCV
from sklearn.metrics import mean_squared_error

# ajusta o modelo ridge regression
ridge2 = Ridge(alpha = 0, normalize = True)
ridge2.fit(X_train, y_train)             # Fit a ridge regression on the training data
y_pred = ridge2.predict(X_test)           # Use this model to predict the test data
RSME = mean_squared_error(y_test, y_pred)
print("RSME:", RSME)          # Calculate the test MSE

RSME: 127487.05257542149


In [8]:
from sklearn.linear_model import Ridge, RidgeCV
from sklearn.metrics import mean_squared_error

# ajusta o modelo ridge regression
ridge2 = Ridge(alpha = 3, normalize = True)
ridge2.fit(X_train, y_train)             # Fit a ridge regression on the training data
y_pred = ridge2.predict(X_test)           # Use this model to predict the test data
RSME = mean_squared_error(y_test, y_pred)
print("RSME:", RSME)          # Calculate the test MSE

RSME: 153483.22038906734
