# <font color="blue"> MBA em Ciência de Dados</font>
# <font color="blue">Programação para Ciência de Dados</font>

## <font color="blue">Numpy Parte I - Avaliação</font>
**Material Produzido por Luis Gustavo Nonato**<br>
**Cemeai - ICMC/USP São Carlos**

### <font color='red'> As respostas da avaliação devem ser inseridas no moodle </font>

In [1]:
import numpy as np

### Exercício 1)
Considere o array `X` como descrito abaixo:
```python
[[0  1  2  3  4]
 [5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
```
Qual dos códigos abaixo retorna uma __view__ contendo a submatriz
```python
[[6  7]
 [11 12]]
```


a) print(X[1,2])<br>
b) print(X[[2,2,3,3],[2,3,2,3]]) <br>
c) print(X[:,[2,3,1])<br>
d) print(X[1:3,1:3])

In [15]:
X=np.array([[0,  1,  2,  3,  4],
 [5,  6,  7,  8,  9],
 [10, 11, 12, 13, 14],
 [15, 16, 17, 18, 19]])

# Solucao
print(X[1:3,1:3])

[[ 6  7]
 [11 12]]


### Exercício 2)
Considerando o array `X` do exercício 1). Qual dos códigos abaixo retorna a __view__ 
```python
[[ 5  7  8]
 [10 12 13]]

```
a) print(X[1:3,0:2:3]])<br>
b) print(X[1:3,[0,2,3]])<br>
c) print(X[1:3,:3])<br>
d) print(X[[1,2,3],[0,2,3]])

In [16]:
# Solucao
print(X[1:3][:,[0,2,3]])
print('\n')
print(X[1:3,[0,2,3]])

[[ 5  7  8]
 [10 12 13]]


[[ 5  7  8]
 [10 12 13]]


### Exercício 3)
Considere o array `A`:
```python
[[ 2 19 16  1 12  7]
 [ 5 19 18 17  9  3]
 [16  4 18 11  4  2]
 [ 6  2 18 14 15 15]
 [ 4  8  1 14 1 13]]
```
Qual das alternativas abaixo imprime o número de dimensões, o número de entradas em cada dimensão e ao número de elementos no array, respectivamente?

a) print(A.itemsize, A.shape, A.ndim)<br>
b) print(A.ndim, A.itemsize, A.shape)<br>
c) print(A.shape, A.dtype, A.size)<br>
d) print(A.ndim, A.shape, A.size)

In [22]:
A = np.array([[ 2, 19, 16,  1, 12,  7],
 [ 5, 19, 18, 17,  9,  3],
 [16,  4, 18, 11,  4,  2],
 [ 6,  2, 18, 14, 15, 15],
 [ 4,  8,  1, 14, 1, 13]])

# Solucao
print(A.ndim)
print(A.shape)
print(A.size)

2
(5, 6)
30


### Exercício 4) 
Considere o numpy array `A` do exercício anterior. Escreva um código para criar uma máscara booleana para selecionar todos os elementos **estritamente** menores que 10 no array e armazena-los em um novo array unidimensional `B`. O resultado do comando
```python
print(B.size)
```
será:<br>

a) 13<br>
b) 14<br>
c) 15<br>
d) 16

In [35]:
# mask = Solucao
mask = (A < 10)
B = A[mask]
print(A)
print('\n',B)
print(B.size)



[[ 2 19 16  1 12  7]
 [ 5 19 18 17  9  3]
 [16  4 18 11  4  2]
 [ 6  2 18 14 15 15]
 [ 4  8  1 14  1 13]]

 [2 1 7 5 9 3 4 4 2 6 2 4 8 1 1]
15


### Exercício 5)
Ainda considerando o array `A` do exercício 3), que alternativa melhor explica o que o código abaixo está realizando:
```python
l_mask = [(i%2==0) and (j%2==0) for i in range(A.shape[0]) for j in range(A.shape[1])]
mask = np.array(l_mask).reshape(A.shape)
A[mask] = -1
```
a) insere -1 nos elementos das linhas pares de `A`<br>
b) insere -1 nas nas linhas ou colunas pares de `A` utilizando uma máscara booleana<br>
c) insere -1 nos elementos cujo índice da linha e da coluna de `A` são pares<br>
c) troca os elementos pares da matriz por -1 

In [39]:
l_mask = [(i%2==0) and (j%2==0) for i in range(A.shape[0]) for j in range(A.shape[1])]
mask = np.array(l_mask).reshape(A.shape)
A[mask] = -1
print(A)

[[-1 19 -1  1 -1  7]
 [ 5 19 18 17  9  3]
 [-1  4 -1 11 -1  2]
 [ 6  2 18 14 15 15]
 [-1  8 -1 14 -1 13]]
