# <span style="color:blue"> MBA em Ciência de Dados</span>
# <span style="color:blue">Programação para Ciência de Dados</span>

## <span style="color:blue">Numpy Parte I - Exercícios</span>
**Material Produzido por Luis Gustavo Nonato**<br>
**Cemeai - ICMC/USP São Carlos**

#### <span style="color:red">Recomenda-se fortemente que os exercícios sejam feitos sem consultar as respostas antecipadamente.</span>

In [3]:
import numpy as np

### Exercício 1)
Utilize comprehension para gerar a lista de todos os números interios entre 0 e 19. Converta a lista em um <font color='blue'>numpy</font> array bidimensional (matriz) com 4 linhas e 5 colunas.

In [37]:
l = [i for i in range(20)]
A = np.array(l).reshape(4,5)
print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


### Exercício 2)
Construa um array unidimensional com 30 números inteiros escolhidos de forma randômica no intervalo entre 0 e 20. Reformate o array para que se torne uma matriz `A` com 5 linhas e 6 colunas.

In [4]:
A = np.random.randint(0,20,30).reshape(5,6)
print(A)

[[ 0  4 18 12  5 19]
 [ 1  0  8  8 17 17]
 [ 9 16 12 19 12 14]
 [ 5  6  1 16 11 12]
 [11 19 17  2 11 12]]


### Exercício 3)
Crie uma __view__ da matriz `A` gerada na célula anterior contendo:
- as linhas de `A` com índices 0,1 e 3
- as linhas de `A` com índice 1 e 2 e as colunas com índice 0,2 e 4
- as linhas de `A` com índice 1 e 3 e as colunas com índice 1 e 3

In [8]:
print('Matriz A:')
print(A,'\n')

A0 = A[[0,1,3]] # linhas de `A` com índices 0,1 e 3
print("linhas de `A` com indices 0,1 e 3")
print(A0,'\n')

A1 = A[1:3,[0,2,4]] # linhas de `A` com índice 1 e 2 e as colunas com índice 0,2 e 4
print("linhas de `A` com indice 1 e 2 e colunas com indice 0,2 e 4")
print(A1,'\n')

A2 = A[[1,3],:][:,[1,3]] #linhas de `A` com índice 1 e 3 e as colunas com índice 1 e 3
print("linhas de `A` com indice 1 e 3 e colunas com indice 1 e 3")
print(A2)

A22 = A[[1,3],[1,3]]
print(A22)

Matriz A:
[[ 0  4 18 12  5 19]
 [ 1  0  8  8 17 17]
 [ 9 16 12 19 12 14]
 [ 5  6  1 16 11 12]
 [11 19 17  2 11 12]] 

linhas de `A` com indices 0,1 e 3
[[ 0  4 18 12  5 19]
 [ 1  0  8  8 17 17]
 [ 5  6  1 16 11 12]] 

linhas de `A` com indice 1 e 2 e colunas com indice 0,2 e 4
[[ 1  8 17]
 [ 9 12 12]] 

linhas de `A` com indice 1 e 3 e colunas com indice 1 e 3
[[ 0  8]
 [ 6 16]]
[ 0 16]


### Exercício 4)
Construa um array `A` bidimensional 5x6 com 30 números inteiros escolhidos de forma randômica no intervalo entre 0 e 20. 
- faça uma cópia do array `A` criado, chamando a cópia de `Ac`
- Substitua todos os elementos do array `A` que sejam maiores que 10 pelo valor -1 
- Substitua todos os elementos do array `Ac` que sejam maiores que 7 e menores que 15 pelo valor -1 

__Dica:__ Gere máscaras booleanas para realizar as modificações nos arrays.

In [25]:
A = np.random.randint(0,20,30).reshape(5,6)
print('A original')
print(A)

Ac = np.copy(A)  # copia de A

maskA = (A > 10)
A[maskA]  = -1
print('\nA modificada com -1 para elementos maiores que 10')
print(A)

maskAc = ((Ac > 7) & (Ac < 15))
Ac[maskAc] = -1
print('\nAc modificada com -1 para elementos maiores que 7 e menores que 15')
print(Ac)

A original
[[13 16  3  6 13 18]
 [ 6 19  1  1  1  9]
 [18  4 17 11  7  2]
 [ 2 19  8  7  8 19]
 [19  1  3  5 12 17]]

A modificada com -1 para elementos maiores que 10
[[-1 -1  3  6 -1 -1]
 [ 6 -1  1  1  1  9]
 [-1  4 -1 -1  7  2]
 [ 2 -1  8  7  8 -1]
 [-1  1  3  5 -1 -1]]

Ac modificada com -1 para elementos maiores que 7 e menores que 15
[[-1 16  3  6 -1 18]
 [ 6 19  1  1  1 -1]
 [18  4 17 -1  7  2]
 [ 2 19 -1  7 -1 19]
 [19  1  3  5 -1 17]]


### Exercício 5)
Construa um array `A` com 20 linhas e 10 colunas onde os elementos são os números interios de  1 até 200.
- Crie uma __view__ de `A` chamada `A_lpares` contendo apenas as linhas de `A` com índice par. 
- Crie uma __view__ de `A` chamada `A_lpares_cimpares` contendo as linhas `A` com índice par e colunas com índice ímpar. 

In [2]:
import numpy as np

A = np.arange(1,201).reshape(20,10)
print(A)

A_lpares = A[np.arange(0,A.shape[0],2)]
print('A_lpares')
print(A_lpares)

print('\nA_lpares_cimpares')
A_lpares_cimpares = A[np.arange(0,A.shape[0],2)][:,np.arange(1,A.shape[1],2)]
print(A_lpares_cimpares)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]
 [101 102 103 104 105 106 107 108 109 110]
 [111 112 113 114 115 116 117 118 119 120]
 [121 122 123 124 125 126 127 128 129 130]
 [131 132 133 134 135 136 137 138 139 140]
 [141 142 143 144 145 146 147 148 149 150]
 [151 152 153 154 155 156 157 158 159 160]
 [161 162 163 164 165 166 167 168 169 170]
 [171 172 173 174 175 176 177 178 179 180]
 [181 182 183 184 185 186 187 188 189 190]
 [191 192 193 194 195 196 197 198 199 200]]
A_lpares
[[  1   2   3   4   5   6   7   8   9  10]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 41  42  43  44  45  46  47  48  49  50]
 

### Exercício 6)
Substitua os elememtos do array `A` do exercício anterior por -1 quando pelo menos um dos índices do elemento é par. 

__Dica:__ Construa uma máscara booleana

In [3]:
mask = [(i%2==0) or (j%2==0) for i in range(A.shape[0]) for j in range(A.shape[1])]
mask = np.array(mask).reshape(A.shape[0],A.shape[1])
A[mask] = -1

print(A)

[[ -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [ -1  12  -1  14  -1  16  -1  18  -1  20]
 [ -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [ -1  32  -1  34  -1  36  -1  38  -1  40]
 [ -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [ -1  52  -1  54  -1  56  -1  58  -1  60]
 [ -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [ -1  72  -1  74  -1  76  -1  78  -1  80]
 [ -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [ -1  92  -1  94  -1  96  -1  98  -1 100]
 [ -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [ -1 112  -1 114  -1 116  -1 118  -1 120]
 [ -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [ -1 132  -1 134  -1 136  -1 138  -1 140]
 [ -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [ -1 152  -1 154  -1 156  -1 158  -1 160]
 [ -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [ -1 172  -1 174  -1 176  -1 178  -1 180]
 [ -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [ -1 192  -1 194  -1 196  -1 198  -1 200]]


### Exercício 7)
Considere o array `X` de números tipo <font color='blue'>float</font> gerado a partir de uma distribuição uniforme no intervalo entre 0 e 1. Escreva um código para encontrar os três menores valores do array.

__Dica:__ Converta o array em uma lista e ordene.

In [43]:
X = np.random.uniform(0,1,30).reshape(6,5)
print(X)

X_sorted = sorted(X.ravel())
print('Os tres menores valores: ',X_sorted[0:3])

[[0.94748436 0.12077873 0.84379874 0.50442844 0.17350562]
 [0.24090184 0.49661223 0.34987579 0.65687144 0.71152296]
 [0.25611281 0.88350259 0.34793285 0.86249615 0.29025411]
 [0.89750685 0.00630518 0.07010046 0.80715441 0.46074591]
 [0.64143342 0.09910184 0.91231711 0.61800674 0.82763288]
 [0.95331726 0.61571514 0.90530625 0.36655696 0.52327298]]
Os tres menores valores:  [0.006305182092773309, 0.07010045904101359, 0.09910183739383205]


### Exercício 8)
Escreva uma função chamada `troca_colunas` que recebe um array e o índice de duas colunas como parâmetros e retorna o array com as colunas trocadas. Por exemplo:
```python
X = np.array([[0, 1, 2, 3, 4, 5], 
              [0, 1, 2, 3, 4, 5], 
              [0, 1, 2, 3, 4, 5]])

X = troca_colunas(X,1,3)
print(X)
```
deve resultar em
```python
[[0 3 2 1 4 5]
 [0 3 2 1 4 5]
 [0 3 2 1 4 5]]
```


In [13]:
def troca_colunas(A,i,j):
    aux = np.copy(A[:,i])
    A[:,i] = A[:,j]
    A[:,j] = aux
    return(A)

X = np.array([[0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4, 5]])
print(X)

X = troca_colunas(X,1,3)
print(X)

[[0 1 2 3 4 5]
 [0 1 2 3 4 5]
 [0 1 2 3 4 5]]
[[0 3 2 1 4 5]
 [0 3 2 1 4 5]
 [0 3 2 1 4 5]]


### Exercício 9)
Os métodos <font color='blue'>vstack</font> e <font color='blue'>hstack</font> do <font color='blue'>numpy</font> empilha matrizes na vertical e horizontal, respectivamente. Por exemplo:
```python
A = np.array([[1.0, 1.0, 1.0], [1.0, 1.0, 1.0]])
B = np.array([[2.0, 2.0, 2.0], [2.0, 2.0, 2.0]])

C = np.vstack((A,B))
print(C)
```
resulta em
```python
[[1. 1. 1.]
 [1. 1. 1.]
 [2. 2. 2.]
 [2. 2. 2.]]
```
Escreva um código para gerar duas matrizes `A` e `B` de números inteiros randômicos no intervalo entre 0 e 10, onde:
- A matriz `A` é 5x6
- A matriz `B` é 5x3

Utilize o método <font color='blue'>hstack</font> para empilhar as matrizes

O que acontece se tentar utilizar o método <font color='blue'>vstack</font>? Explique o motivo da mensagem gerada.

In [20]:
A = np.random.randint(0,10,30).reshape(5,6)
B = -1*np.random.randint(0,10,15).reshape(5,3)
print(A)
print(B)

C = np.hstack((A,B))
print(C)

# o método vstack nao pode ser utilizado pois o número de colunas 
# não é o mesmo nas duas matrizes, somente o número de linhas coincide

[[6 1 9 7 8 2]
 [3 5 8 5 3 1]
 [0 9 9 2 2 3]
 [5 8 9 8 6 4]
 [8 2 0 4 9 6]]
[[-5 -9 -4]
 [-6 -3 -5]
 [-6 -5 -2]
 [-7 -1 -4]
 [-7 -9 -8]]
[[ 6  1  9  7  8  2 -5 -9 -4]
 [ 3  5  8  5  3  1 -6 -3 -5]
 [ 0  9  9  2  2  3 -6 -5 -2]
 [ 5  8  9  8  6  4 -7 -1 -4]
 [ 8  2  0  4  9  6 -7 -9 -8]]


### Exercício 10)
Escreva um código para, data uma matriz, zerar todos os elementos abaixo da diagonal principal da matriz. Por exemplo:
```python
[[2 8 3 4 8]
 [4 8 7 7 3]
 [8 2 3 1 4]
 [8 6 3 8 1]
 [6 4 4 6 1]]
```
deve resultar em
```python
[[2 8 3 4 8]
 [0 8 7 7 3]
 [0 0 3 1 4]
 [0 0 0 8 1]
 [0 0 0 0 1]]
```

In [29]:
A = np.random.randint(1,10,25).reshape(5,5)

mask = [True if i>j else False for i in range(A.shape[0]) for j in range(A.shape[1])]
mask = np.array(mask).reshape(A.shape[0],A.shape[1])
print(mask)

A[mask] = 0
print(A)

# uma alternativa é utilizar o método 'triu' do numpy
A = np.random.randint(1,10,25).reshape(5,5)
print(A)
A = np.triu(A)
print(A)

[[False False False False False]
 [ True False False False False]
 [ True  True False False False]
 [ True  True  True False False]
 [ True  True  True  True False]]
[[7 4 4 9 3]
 [0 8 4 5 4]
 [0 0 9 4 7]
 [0 0 0 8 7]
 [0 0 0 0 2]]
[[2 8 3 4 8]
 [4 8 7 7 3]
 [8 2 3 1 4]
 [8 6 3 8 1]
 [6 4 4 6 1]]
[[2 8 3 4 8]
 [0 8 7 7 3]
 [0 0 3 1 4]
 [0 0 0 8 1]
 [0 0 0 0 1]]
