### Trabalhando com um array com mais dimensões

In [41]:
import numpy as np

arr = np.array([[1,2,3,4],[5,6,7,8],[9, 10, 11, 2]], ndmin=4)

print(arr)
print('number of dimensions :', arr.ndim)
arr[0][0][1][1]

[[[[ 1  2  3  4]
   [ 5  6  7  8]
   [ 9 10 11  2]]]]
number of dimensions : 4


6

### Atributo dtype - Define os valores para sua matriz

https://numpy.org/doc/stable/reference/arrays.dtypes.html

In [18]:
import numpy as np

arr1 = np.array([1, 2, 3, 4], dtype='S')

print(arr1)
print(arr1.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [19]:
type(arr1[0])

numpy.bytes_

In [20]:
arr1[0]

b'1'

In [29]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='i2')

print(arr)
print(arr.dtype)

[1 2 3 4]
int16


In [42]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [45]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype="i4")

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [48]:
import numpy as np

arr = np.array(['a', '2', '3'], dtype='i')
arr

ValueError: invalid literal for int() with base 10: 'a'

In [47]:
import numpy as np

arr = np.array(['1', '2', '3'], dtype='i')
arr

array([1, 2, 3], dtype=int32)

In [33]:
import numpy as np

arr1 = np.array(["a", 2, 3, 4], dtype=str)

print(arr1)
print(arr1.dtype)

['a' '2' '3' '4']
<U1


In [36]:
arr1[1]/2

TypeError: unsupported operand type(s) for /: 'numpy.str_' and 'int'

In [50]:
import numpy as np

arr1 = np.array([1, 2, 3, 4], dtype="U")

print(arr1)
print(arr1.dtype)

['1' '2' '3' '4']
<U1


### Atributo .base para copy e view - Aponta se o objeto obtém a matriz

https://numpy.org/doc/stable/reference/generated/numpy.ndarray.base.html

In [26]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


### Reshape de 1-D para 3-D

In [27]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


### Reshape com o valor -1

In [59]:
arr = np.array([[1, 2, 3], [4, 5, 6],[4, 5, 6]])

print(arr)

newarr = arr.reshape(-1)

print(newarr)

[[1 2 3]
 [4 5 6]
 [4 5 6]]
[1 2 3 4 5 6 4 5 6]


### Reshape não altera o valor inicial

In [60]:
a=np.arange(9)
print(a.reshape(3,3))
print(a)


a=np.arange(9)
a = a.reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [68]:
a=np.arange(9)
a = np.resize(a,(3,3))
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### nditer - forma de iterar mais facilmente sobre um array mais complexo
https://numpy.org/doc/stable/reference/generated/numpy.nditer.html

In [69]:
import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)


for idx, x in np.ndenumerate(arr):
  print(idx, x)

1
2
3
4
5
6
7
8
(0, 0, 0) 1
(0, 0, 1) 2
(0, 1, 0) 3
(0, 1, 1) 4
(1, 0, 0) 5
(1, 0, 1) 6
(1, 1, 0) 7
(1, 1, 1) 8


### ndenumerate - uma forma de termos index e o valor em conjunto 
https://numpy.org/doc/stable/reference/generated/numpy.ndenumerate.html

In [34]:
import numpy as np

arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [35]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


### dstack - depth (profundidade) stack 

https://numpy.org/doc/stable/reference/generated/numpy.dstack.html

In [39]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [40]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [41]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


### Where - descobrindo o index de valores específicos

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [71]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

x = np.where(arr == 4)

print(x)

(array([3], dtype=int64),)


In [73]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([], dtype=int64),)


In [74]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 10)

print(x)

(array([], dtype=int64),)


### np.argmax - Obtendo o valor máximo de um array;

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [75]:
a = np.arange(6).reshape(2,3) + 10
print(a)

[[10 11 12]
 [13 14 15]]


In [76]:
np.argmax(a)

5

In [78]:
np.argmin(a)

0

In [60]:
np.argmax(a, axis=1)

array([2, 2], dtype=int64)

In [77]:
np.argmin(a, axis=1)

array([0, 0], dtype=int64)