# <font color="blue"> MBA em Ciência de Dados</font>
# <font color="blue">Programação para Ciência de Dados</font>

## <font color="blue">Numpy Parte II e Matplotlib - Avaliação</font>
**Material Produzido por Luis Gustavo Nonato**<br>
**Cemeai - ICMC/USP São Carlos**
---

In [1]:
import numpy as np
import matplotlib.pyplot as plt

### Exercício 1)
Qual dos códigos abaixo utiliza corretamente broadcasting para somar o vetor `v` em cada **coluna** da matriz `A`, sendo que `v` e `A` são definidos como:
```python
A = np.zeros((4,4))
v = np.arange(4)
```

a) A[,:] + v<br>
b) A + v<br>
c) A + v.T<br>
d) A + v.reshape(4,1)

In [20]:
A = np.zeros((4,4))
v = np.arange(4)

B = A + v.reshape(4,1)

print(v)
print(A.shape, v.shape, v.T.shape, v.reshape(4,1).shape)
print('\n',B)

[0 1 2 3]
(4, 4) (4,) (4,) (4, 1)

 [[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]]


### Exercício 2)
Qual das alternativas explica corretamente como o array `W` está sendo calculado no código abaixo?
```python
u = np.random.randint(0,30,7)
v = np.random.randint(0,30,10).reshape(10,1)

W = v + u
```

a) O array `W` possui 10 elementos como resultado da soma dos arrays `u` e `v`, onde `u` é complementado com zeros durante o broadcasting.<br>
b) O array `W` possui 7 elementos como resultado da soma dos arrays `u` e `v`, onde os três útlimos elementos de `v` são descartados no broadcasting.<br>
c) O array `W` é uma matriz com 7 linhas e 10 colunas gerado a partir da soma das matriz obtidas do broadcasting do array `v` em 7 linhas e o array `u` em 10 linhas.<br>
d) O array `W` é uma matriz com 10 linhas e 7 colunas gerado a partir da soma das matriz obtidas do broadcasting do array `v` em 7 colunas e do array `u` em 10 linhas.<br>

In [57]:
u = np.random.randint(0,30,7)
v = np.random.randint(0,30,10).reshape(10,1)

W = v + u

print(W.shape, v.shape, u.shape)
print(u)
print(W.size)
print('\n',W)


(10, 7) (10, 1) (7,)
[ 9 29 12 12  3 17 22]
70

 [[21 41 24 24 15 29 34]
 [32 52 35 35 26 40 45]
 [21 41 24 24 15 29 34]
 [34 54 37 37 28 42 47]
 [32 52 35 35 26 40 45]
 [24 44 27 27 18 32 37]
 [37 57 40 40 31 45 50]
 [33 53 36 36 27 41 46]
 [22 42 25 25 16 30 35]
 [26 46 29 29 20 34 39]]


### Exercício 3)
Considere a matriz abaixo. Utilizando redução por média, encontre o **índice da linha** que possui a maior média dos elementos.
```python
A = np.array([[5, 2, 3, 6, 1, 5, 7, 7, 8, 9], [8, 8, 3, 5, 0, 1, 4, 8, 3, 7], 
              [8, 0, 0, 4, 2, 0, 2, 6, 0, 3], [5, 0, 0, 4, 4, 3, 5, 8, 0, 0], 
              [2, 4, 2, 5, 3, 4, 9, 8, 0, 0], [6, 7, 4, 8, 5, 1, 3, 5, 4, 1], 
              [6, 8, 0, 5, 2, 9, 3, 6, 1, 6], [5, 5, 2, 9, 0, 5, 5, 8, 2, 4], 
              [8, 8, 1, 8, 4, 1, 8, 9, 7, 6], [5, 6, 0, 9, 0, 4, 9, 0, 2, 0]])
```
a) linha de índice 8<br>
b) linha de índice 0<br>
c) linha de índice 5<br>
d) linha de índice 9

In [44]:
A = np.array([[5, 2, 3, 6, 1, 5, 7, 7, 8, 9], [8, 8, 3, 5, 0, 1, 4, 8, 3, 7], 
              [8, 0, 0, 4, 2, 0, 2, 6, 0, 3], [5, 0, 0, 4, 4, 3, 5, 8, 0, 0], 
              [2, 4, 2, 5, 3, 4, 9, 8, 0, 0], [6, 7, 4, 8, 5, 1, 3, 5, 4, 1], 
              [6, 8, 0, 5, 2, 9, 3, 6, 1, 6], [5, 5, 2, 9, 0, 5, 5, 8, 2, 4], 
              [8, 8, 1, 8, 4, 1, 8, 9, 7, 6], [5, 6, 0, 9, 0, 4, 9, 0, 2, 0]])

media = np.mean(A, axis = 1)
indice_media = np.argmax(media)

print(A)
print('\n A media de cada linha é: ',media)
print('A linha com maior media esta na posição: ',indice_media)

[[5 2 3 6 1 5 7 7 8 9]
 [8 8 3 5 0 1 4 8 3 7]
 [8 0 0 4 2 0 2 6 0 3]
 [5 0 0 4 4 3 5 8 0 0]
 [2 4 2 5 3 4 9 8 0 0]
 [6 7 4 8 5 1 3 5 4 1]
 [6 8 0 5 2 9 3 6 1 6]
 [5 5 2 9 0 5 5 8 2 4]
 [8 8 1 8 4 1 8 9 7 6]
 [5 6 0 9 0 4 9 0 2 0]]

 A media de cada linha é:  [5.3 4.7 2.5 2.9 3.7 4.4 4.6 4.5 6.  3.5]
A linha com maior media esta na posição:  8


### Exercício 4) 
Considerando a matriz `A` do exercício anterior, qual o **índice da coluna** que possui a menor soma de valores?

a) linha 8<br>
b) linha 0<br>
c) linha 2<br>
d) linha 9

In [52]:
# Solucao

A = np.array([[5, 2, 3, 6, 1, 5, 7, 7, 8, 9], [8, 8, 3, 5, 0, 1, 4, 8, 3, 7], 
              [8, 0, 0, 4, 2, 0, 2, 6, 0, 3], [5, 0, 0, 4, 4, 3, 5, 8, 0, 0], 
              [2, 4, 2, 5, 3, 4, 9, 8, 0, 0], [6, 7, 4, 8, 5, 1, 3, 5, 4, 1], 
              [6, 8, 0, 5, 2, 9, 3, 6, 1, 6], [5, 5, 2, 9, 0, 5, 5, 8, 2, 4], 
              [8, 8, 1, 8, 4, 1, 8, 9, 7, 6], [5, 6, 0, 9, 0, 4, 9, 0, 2, 0]])

sum_col = np.sum(A, axis = 0)
indice_sum = np.argmin(sum_col)

print(A)
print('\n A soma de cada coluna é: ',sum_col)
print('A coluna com menor soma esta na posição: ',indice_sum)


[[5 2 3 6 1 5 7 7 8 9]
 [8 8 3 5 0 1 4 8 3 7]
 [8 0 0 4 2 0 2 6 0 3]
 [5 0 0 4 4 3 5 8 0 0]
 [2 4 2 5 3 4 9 8 0 0]
 [6 7 4 8 5 1 3 5 4 1]
 [6 8 0 5 2 9 3 6 1 6]
 [5 5 2 9 0 5 5 8 2 4]
 [8 8 1 8 4 1 8 9 7 6]
 [5 6 0 9 0 4 9 0 2 0]]

 A soma de cada coluna é:  [58 48 15 63 21 33 55 65 27 36]
A coluna com menor soma esta na posição:  2
(10, 10)


### Exercício 5)
Suponha que a variável `A` no código abaixo é uma matriz com $n$ linhas e $m$ colunas. O que o código está realizando?
```python
Aargs = np.argsort(A)
A[np.arange(A.shape[0]),Aargs[:,0]] = -1
```
a) Substituindo o maior valor de cada coluna por -1<br>
b) Substituindo o maior valor de cada linha por -1<br>
c) Substituindo o menor valor de cada linha por -1<br>
d) Substituindo o menor valor de cada coluna por -1

In [ ]:
# Solucao
